"""five

Revision ID: 4178a9799b8c
Revises: 9e6691159604
Create Date: 2021-04-05 19:41:07.930611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4178a9799b8c'
down_revision = '9e6691159604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newss', sa.Column('description', sa.String(length=500), nullable=False))
    op.add_column('newss', sa.Column('title', sa.String(length=170), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newss', 'title')
    op.drop_column('newss', 'description')
    # ### end Alembic commands ###
