"""three

Revision ID: 78aa70e11fcd
Revises: b53336444d02
Create Date: 2021-04-05 19:28:06.194798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aa70e11fcd'
down_revision = 'b53336444d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newss', sa.Column('description', sa.String(length=500), nullable=False))
    op.add_column('newss', sa.Column('title', sa.String(length=170), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newss', 'title')
    op.drop_column('newss', 'description')
    # ### end Alembic commands ###
