"""four

Revision ID: 9e6691159604
Revises: 78aa70e11fcd
Create Date: 2021-04-05 19:40:50.723214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6691159604'
down_revision = '78aa70e11fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newss', 'title')
    op.drop_column('newss', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newss', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('newss', sa.Column('title', sa.VARCHAR(length=170), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
