"""sixs

Revision ID: b7fea7cf0b12
Revises: 628e6b22965b
Create Date: 2021-04-05 19:42:42.760038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fea7cf0b12'
down_revision = '628e6b22965b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newss', 'title',
               existing_type=sa.VARCHAR(length=170),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newss', 'title',
               existing_type=sa.VARCHAR(length=170),
               nullable=True)
    # ### end Alembic commands ###
